server:
  port: 8081
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-alias: server
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:truststore.jks
    trust-store-password: secret
    trust-store-type: JKS

security:
  enabled: false
  jwt:
    secret: javainusegn54m4b5jkn45bjnkjafusdbfhasbvh2n34jv234n23javainusegn54m4b5jkn45bjnkjafusdbfhasbvh2n34jv234n23javainusegn54m4b5jkn45bjnkjafusdbfhasbvh2n34jv234n23


